app/blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostListByCategoryView

app_name = 'blog'


urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('posts/<slug>', PostDetailView.as_view(), name='detail'),
    path('category/<slug>', PostListByCategoryView.as_view(), name='category'),
]

app/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap, StaticSitemap


admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_INDEX_TITLE


sitemaps = {
    'posts': PostSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', include('blog.urls')),
    path(settings.ADMIN_URL + '/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

app/blog/models.py
from django.contrib.sitemaps import ping_google
from django.db import models
from django.utils.safestring import mark_safe


class Category(models.Model):
    name = models.CharField(verbose_name='名前', max_length=250, unique=True)
    slug = models.SlugField(verbose_name='URL', max_length=250, unique=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name = 'カテゴリー'
        verbose_name_plural = 'カテゴリー'

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(verbose_name='タイトル', max_length=160)
    description = models.TextField(verbose_name='ディスクリプション', max_length=240)
    slug = models.SlugField(verbose_name='URL', max_length=250, unique=True)
    category = models.ForeignKey(
        Category, verbose_name='カテゴリー', on_delete=models.PROTECT
    )
    eyecatch = models.ImageField(
        verbose_name='サムネイル', upload_to='uploads/', max_length=320, blank=True
    )
    content = models.TextField(verbose_name='本文', max_length=50000)
    is_published = models.BooleanField(verbose_name='公開', default=False)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    @property
    def post_eyecatch(self):
        return mark_safe(
            '<image src="%s" style="width:100px;height:auto;"/>'
            % self.eyecatch.url
        )

    class Meta:
        verbose_name = '記事'
        verbose_name_plural = '記事'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            ping_google()
        except Exception:
            pass

app/common/models.py
from django.db import models


class Setting(models.Model):
    site_name = models.CharField(verbose_name='サイト名', max_length=160)
    site_description = models.TextField(verbose_name='サイトの説明', max_length=240)
    ogp_image = models.ImageField(
        verbose_name='OGP画像', upload_to='uploads/', max_length=320, blank=True
    )
    profile_icon = models.ImageField(
        verbose_name='プロフィール画像',
        upload_to='uploads/',
        max_length=320,
        blank=True
    )
    profile_info = models.TextField(verbose_name='プロフィール情報', max_length=240)
    ga_tag = models.TextField(
        verbose_name='GoogleAnalyticsタグ', max_length=600, blank=True
    )
    email = models.CharField(
        verbose_name='メールアドレス', max_length=240, blank=True
    )
    twitter = models.CharField(
        verbose_name='Twitter', max_length=240, blank=True
    )
    github = models.CharField(
        verbose_name='GitHub', max_length=240, blank=True
    )
    is_public = models.BooleanField(
        verbose_name='検索エンジンに登録する', default=True
    )
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name = 'サイト基本情報'
        verbose_name_plural = 'サイト基本情報'

    def __str__(self):
        return self.site_name

app/blog/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Post, Category


class PostListView(ListView):
    model = Post
    queryset = Post.objects.filter(is_published=True).order_by('-created_at')
    paginate_by = 12
    context_object_name = 'posts'


class PostDetailView(DetailView):
    model = Post


class PostListByCategoryView(ListView):
    model = Post
    paginate_by = 12
    context_object_name = 'posts'
    template_name = 'blog/post_category.html'

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs['slug'])
        queryset = Post.objects.order_by('-created_at').filter(
            category=category
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(
            Category, slug=self.kwargs['slug']
        )
        return context

app/templates/blog/base.html
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta property="og:title" content="{% block og_title %}{% endblock %}" />
    <meta property="og:description" content="{% block og_description %}{% endblock %}" />
    <meta property="og:type" content="{% block ogp_type %}{% endblock %}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="{% block og_image %}{% endblock %}" />
    <meta property="og:site_name" content="{{ setting.site_name }}" />
    <meta property="og:locale" content="ja_JP" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@{{ setting.twitter }}" />
    <meta name="twitter:description" content="{% block tw_description %}{% endblock %}" />
    <meta name="twitter:image" content="{% block tw_image %}{% endblock %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP|Patua+One" rel="stylesheet">
    {% if not setting.is_public %}<meta name=”robots” content="noindex,nofollow">{% endif %}
    {% if setting.ga_tag %}{% autoescape off %}{{ setting.ga_tag }}{% endautoescape %}{% endif %}
  </head> 
  <body>
    <header>
      {% block header_tag %}{% endblock %}
    </header>
      {% block content %}{% endblock %}
    <footer>
      <div>
        {% if setting.email %}
          <a href="mailto:{{ setting.email }}?subject=お問い合わせ" class="sns-icon" target="_blank">
            <i class="far fa-envelope fa-2x"></i>
          </a>
        {% endif %}
        {% if setting.twitter %}
          <a href="https://twitter.com/{{ setting.twitter }}" class="sns-icon" target="_blank">
            <i class="fab fa-twitter fa-2x"></i>
          </a>
        {% endif %}
        {% if setting.github %}
          <a href="https://github.com/{{ setting.github }}" class="sns-icon" target="_blank">
            <i class="fab fa-github-alt fa-2x"></i>
          </a>
        {% endif %}
      </div>
      Copyright - {{ setting.site_name }} . 2019 All Rights Reserved.
    </footer>
    {% block script %}{% endblock %}
  </body>
</html>

app/templates/blog/includes/pagination.html
{% if page_obj.has_previous or page_obj.has_next %}
  <div class="pagination">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}" class="prev">← Prev Page</a>
    {% endif %}
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="next">Next Page →</a>
    {% endif %}
    <div class="clear"></div>
  </div>
{% endif %}

app/templates/blog/post_category.html
{% extends 'blog/base.html' %}

{% block title %}{{ category.name }}に関する記事一覧{% endblock %}
{% block description %}{{ category.name }}のカテゴリーページです。{% endblock %}
{% block og_title %}{{ category.name }}に関する記事一覧{% endblock %}
{% block og_description %}{{ category.name }}のカテゴリーページです。{% endblock %}
{% block ogp_type %}website{% endblock %}
<!-- {% block og_image %}{{ setting.ogp_image.url }}{% endblock %} -->
{% block tw_description %}{{ category.name }}のカテゴリーページです。{% endblock %}
<!-- {% block tw_image %}{{ setting.ogp_image.url }}{% endblock %} -->

{% block header_tag %}<a href="/" class="alt_title">{{ setting.site_name }}</a>{% endblock %}

{% block content %}
  <h1 class="categoy_title">{{ category.name }}に関する記事一覧</h1>
  {% for post in object_list %}
    <article>
      <h2>{{ post.title }}</h2>
      <p>{{ post.description | truncatechars:105 }}</p>
      <span>{{ post.created_at|date:"Y/m/d" }}</span>
      <a href="{% url 'blog:detail' post.slug %}" class="article-link"></a>
    </article>
  {% endfor %}
  {% include 'blog/includes/pagination.html' %}
{% endblock %}

app/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}{% endblock %}
{% block description %}{{ post.description }}{% endblock %}
{% block og_title %}{{ post.title }}{% endblock %}
{% block og_description %}{{ post.description }}{% endblock %}
{% block ogp_type %}article{% endblock %}
{% block og_image %}{% if post.eyecatch %}{{ post.eyecatch.url }}{% endif %}{% endblock %}
{% block tw_description %}{{ post.description }}{% endblock %}
{% block tw_image %}{% if post.eyecatch %}{{ post.eyecatch.url }}{% endif %}{% endblock %}

{% block header_tag %}<a href="/" class="alt_title">{{ setting.site_name }}</a>{% endblock %}

{% block content %}
  <article class="article_detail">
    <h1 class="alt_post_title">{{ post.title }}</h1>
    <div class="post-info">
      <span>{{ post.created_at|date:"Y/m/d" }}</span>
      <a href="{% url 'blog:category' post.category.slug %}" class="category_btn">
        {{ post.category }}
      </a>
    </div>
    <div class="post-section">
      {% autoescape off %}{{ post.content }}{% endautoescape %}
    </div>
    <div class="share_section">
      <span class="share_span">Share Link:</span>
      <input type="text" value="{{ request.build_absolute_uri }}" id="share_input">
      <span class="copied_repo" id="copied_msg">Link Copied !</span>
    </div>
  </article>
  <div class="btn_back_to_top_section">
    <a href="/" class="btn_back_to_top">TOPページに戻る</a>
  </div>
{% endblock %}

{% block script %}
  <script>
    'use strict';
    var target = document.getElementById('share_input');
    var msg = document.getElementById('copied_msg');

    function copyToClip() {
      target.addEventListener('click', function() {
        target.style.border = '1px solid black';
        target.select();
        document.execCommand("Copy");
        msg.style.display = 'inline-block';
        setTimeout('hideMsg()', 2000);
      });
    }

    function hideMsg() {
      target.style.border = 'none';
      msg.style.display = 'none';
    }

    copyToClip();
  </script>
{% endblock %}

app/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}{{ setting.site_name }}{% endblock %}
{% block description %}{{ setting.site_description }}{% endblock %}
{% block og_title %}{{ setting.site_name }}{% endblock %}
{% block og_description %}{{ setting.site_description }}{% endblock %}
{% block ogp_type %}website{% endblock %}
<!-- {% block og_image %}{{ setting.ogp_image.url }}{% endblock %} -->
{% block tw_description %}{{ setting.site_description }}{% endblock %}
<!-- {% block tw_image %}{{ setting.ogp_image.url }}{% endblock %} -->

{% block header_tag %}
  {% if setting.site_name %}
    <h1><a href="/">{{ setting.site_name }}</a></h1>
  {% endif %}
  {% if setting.profile_info %}
    <div class="profile-section">
      <img src="{{ setting.profile_icon.url }}" class="profile-icon">
      <p class="profile-intro">
        {% autoescape off %}{{ setting.profile_info }}{% endautoescape %}
      </p>
      <div class="clear"></div>
    </div>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in object_list %}
    <article>
      <h2>{{ post.title }}</h2>
      <p>{{ post.description | truncatechars:105 }}</p>
      <span>{{ post.created_at|date:"Y/m/d" }}</span>
      <a href="{% url 'blog:category' post.category.slug %}" class="category_btn">{{ post.category }}</a>
      <a href="{% url 'blog:detail' post.slug %}" class="article-link"></a>
    </article>
  {% endfor %}
  {% include 'blog/includes/pagination.html' %}
{% endblock %}